/// Flutter icons UnitFont
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  UnitFont
///      fonts:
///       - asset: fonts/UnitFont.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class UnitFont {
  UnitFont._();

  static const _kFontFam = 'UnitFont';
  static const _kFontPkg = null;

  static const IconData clock = IconData(0xf017, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ruler = IconData(0xf545, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weight_hanging = IconData(0xf5cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temperature_high = IconData(0xf769, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
